refactor
folder/readdir pull request #1
Opened 2021-04-06 16:09 UTC by jonschlinkert

@doowb please review and give feedback if you see anything that needs to be fixed/improved. Otherwise feel free to merge.

2021-04-06 17:01 UTC, doowb requested changes
Looks awesome!
I left a couple of comments/suggestions inline, but I don't see anything that really sticks out.

2021-04-06 17:01 UTC, doowb commented on lib/async.js
> +  const isMatch = opts.isMatch ? utils.matcher(opts.isMatch, opts) : () => true;
Suggestion: use `noop(true)` here for consistency:

```suggestion
  const isMatch = opts.isMatch ? utils.matcher(opts.isMatch, opts) : noop(true);
```

2021-04-06 17:01 UTC, doowb commented on lib/async.js
> +      if (options.dot === false && file.name[0] !== '.') return;
Is this supposed to be `file.name[0] === '.'`?

```suggestion
      if (options.dot === false && file.name[0] === '.') return;
```

2021-04-06 17:01 UTC, doowb commented on lib/async.js
> +          file.stat = await fs.promises.stat(file[kPath]);
Just curious... any reason to not add `file.isFile()` and `file.isDirectory()` here?

2021-04-06 17:01 UTC, doowb commented on lib/async.js
> +        if (file.isDirectory()) {
Based on my comment above... I'm not assuming that a `Dirent` already has `isFile()` and `isDirectory()`, so when handling the symlinks, those are added to override the default functionality.

2021-04-06 17:01 UTC, doowb commented on lib/sync.js
> +  const isMatch = opts.isMatch ? utils.matcher(opts.isMatch, opts) : () => true;
Same suggestion as in `async`:

```suggestion
  const isMatch = opts.isMatch ? utils.matcher(opts.isMatch, opts) : noop(true);
```

2021-04-06 17:01 UTC, doowb commented on lib/sync.js
> +      if (options.dot === false && file.name[0] !== '.') return;
Same question above...

```suggestion
      if (options.dot === false && file.name[0] === '.') return;
```

2021-04-06 17:01 UTC, doowb commented on lib/async.js
> +    files[unique ? 'add' : 'push'](file[kResult]);
In `sync`, `options.onPush` is called here if it exists... should that be done here too?

2021-04-06 17:01 UTC, doowb commented on package.json
> +  "name": "readdir",
Was this supposed to change?

```suggestion
  "name": "@folder/readdir",
```

2021-04-06 17:02 UTC, doowb commented
@jonschlinkert I left some review comments.

2021-04-07 20:10 UTC, jonschlinkert commented on lib/async.js
> +          file.stat = await fs.promises.stat(file[kPath]);
Yes, since it's not a symbolic link, those functions will already return the correct result.

2021-04-07 20:10 UTC, jonschlinkert commented on lib/async.js
> +        if (file.isDirectory()) {
Correct. No overrides are needed when the file is not a symbolic link.

2021-04-07 20:11 UTC, jonschlinkert commented on lib/async.js
> +    files[unique ? 'add' : 'push'](file[kResult]);
Good catch.

2021-04-07 20:12 UTC, jonschlinkert commented on package.json
> +  "name": "readdir",
Good catch. Not sure how this got changed.

2021-04-08 12:48 UTC, doowb commented on test/readdir.js
> +          assert(files.some(file => path.basename(file) === 'temp'));
Looks like this test is failing because `temp` doesn't exist at this point (it's deleted in `beforeEach`).

2021-04-08 12:53 UTC, doowb commented on test/readdir.js
> +          assert(files.some(file => path.basename(file) === 'temp'));
Oh... I think it's that `temp` just doesn't exist yet in a newly cloned repo. (I just noticed that `temp` isn't deleted, just the files inside)

2021-04-19 08:05 UTC, merged